# Generated by Django 3.1.3 on 2021-02-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_gen', '0004_landingpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
