# Generated by Django 3.1.3 on 2021-02-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_gen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.TextField()),
                ('services_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='testimonial_date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='testimonial_source',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='local_owned_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='bonded_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='emergency_services_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='family_owned_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_image_unsplash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='insured_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='testimonial_hero',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='veteran_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='years_in_business_attribute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='service',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page_gen.landingpage'),
        ),
    ]
