# Generated by Django 3.1.3 on 2021-02-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_gen', '0002_auto_20210205_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='business_hours',
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='company_tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='license_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
