# Generated by Django 3.1.3 on 2021-02-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_gen', '0003_auto_20210205_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
